### ISSUE TITLE
 The process was terminated due to an unhandled exception.  log4net.ElasticSearch.WebElasticClient.FinishGetResponse

### ISSUE THREAD

**Issue by vovikdrg** [jptoto/log4net.ElasticSearch#46]
Application: Crawler.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
Stack:
   at System.Net.HttpWebRequest.EndGetResponse(System.IAsyncResult)
   at log4net.ElasticSearch.WebElasticClient.FinishGetResponse(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.HttpWebRequest.Abort(System.Exception, Int32)
   at System.Net.HttpWebRequest.AbortWrapper(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by jptoto** [comment]
Is this all you have for this issue? Can you provide any more details? WebElastiClient isn't a class that's in log4net.Elasticsearch.

**Comment by vovikdrg** [comment]
well it crashed when ES cluster go down. but I am not sure if you can fix something here. I did mistake when i catch expcetion, i try to log it again... so my app fails.

**Comment by jptoto** [comment]
@vovikdrg This shouldn't happen when the ES cluster is down so I will work on it. I may change the ES call to be "fire and forget" because I don't think we care if the ES cluster responds. If it doesn't, it shouldn't affect the app trying to do the logging.
