### ISSUE TITLE
Timeout crashing application, shouldn't it just write to log4net InternalDebug?

### ISSUE THREAD

**Issue by danielcondemarin** [jptoto/log4net.ElasticSearch#72]
System.InvalidOperationException: An unhandled exception was detected ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at log4net.ElasticSearch.WebElasticClient.FinishGetResponse(IAsyncResult result) in c:\source\log4stash\src\log4net.ElasticSearch\ElasticClient.cs:line 110
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvoke...

**Comment by jptoto** [comment]
@danielcondemarin does this happen during normal operation or are you trying to debug via https://github.com/jptoto/log4net.ElasticSearch/wiki/04-Debugging-log4net.ElasticSearch ?

**Comment by jptoto** [comment]
@danielcondemarin also for what it's worth, log4net calls are blocking so if your Elasticsearch server isn't available, you could see significant performance issues. I may consider adding a timeout in milliseconds to the connection string but you should be careful in production applications.

**Comment by danielcondemarin** [comment]
@jptoto this is happening during normal operation, using log4stash@1.1.1. 
Completely agree with the timeout performance issue, ideally this would be non-blocking.

**Comment by danielcondemarin** [comment]
@jptoto I believe this was fixed https://github.com/urielha/log4stash/commit/823da97e622eab90055464c440d1357ee0382c94
but I didnt get that fix since I'm on 1.1.1 :)

**Comment by jptoto** [comment]
@danielcondemarin since you're not using log4net.Elasticsearch can I close this?
