### ISSUE TITLE
remote server returned an error: (406) Not Acceptable

### ISSUE THREAD

**Issue by shyamhd** [jptoto/log4net.ElasticSearch#91]
Hi, 

I have pull your sample project https://github.com/jptoto/log4net.ES.Example and to debug project I have added `log4net.Util.LogLog.InternalDebugging = true;` while running your project I am getting 
`remote server returned an error: (406) Not Acceptable` error as per below.
```
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
log4net:ERROR [ElasticSearchAppender] ErrorCode: GenericFailure. ElasticSearchAppender [ElasticSearchAppender]: Failed to addd logEvents to Repository in SendBufferCallback.
System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.HttpWebRequest.GetResponse()
   at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T](Uri uri, T items) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Infrastructure\HttpClient.cs:line 69
   at log4net.ElasticSearch.Repository.Add(IEnumerable`1 logEvents, Int32 bufferSize) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Repository.cs:line 40
   at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback(Object state) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\ElasticSearchAppender.cs:line 93
System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.HttpWebRequest.GetResponse()
   at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T](Uri uri, T items) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Infrastructure\HttpClient.cs:line 69
   at log4net.ElasticSearch.Repository.Add(IEnumerable`1 logEvents, Int32 bufferSize) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Repository.cs:line 40
   at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback(Object state) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\ElasticSearchAppender.cs:line 93
System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.HttpWebRequest.GetResponse()
   at log4net.ElasticSearch.Infrastructure.HttpClient.PostBulk[T](Uri uri, T items) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Infrastructure\HttpClient.cs:line 69
   at log4net.ElasticSearch.Repository.Add(IEnumerable`1 logEvents, Int32 bufferSize) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\Repository.cs:line 40
   at log4net.ElasticSearch.ElasticSearchAppender.SendBufferCallback(Object state) in c:\Users\jtoto\projects\log4net.ElasticSearch\src\log4net.ElasticSearch\ElasticSearchAppender.cs:line 93
```
Can you please check this.
Regards,
Shyam

**Comment by shyamhd** [comment]
Issue solved after lots of RND. The solution is that health of elasticsearch was yellow and I converted to green using postman please find below image.

![image](https://user-images.githubusercontent.com/7995684/30845205-f7e52684-a2af-11e7-8cf0-2c9a216c80e7.png)

**Comment by jptoto** [comment]
@shyamhd Sorry for not replying earlier. I cloned my sample project and ran it from VS but I am not having any issues. It works ok. I'm only testing it on my laptop and I use `network.host: 127.0.0.1` in the Elasticsearch config (version 5.6.3) but it's working fine from what I can see.

Have you modified the sample project at all? Perhaps you're attempting to send a message the server doesn't understand?

**Comment by shyamhd** [comment]
@jptoto thank you for reply. 
I have cloned project once again and it is working fine.
I need some help. I am not able to track data from log4net.ES.Example project to kibana.
I have selected `log*` as index pattern. However, not able to track data. I have googled as well.
Can you please help me?

Thanks in advance.

**Comment by jamestoto** [comment]
@shyamhd I may need some more information here. No data is showing in Kibana? Is Kibana correctly connected to Elasticsearch? Does any information show at all in Kibana? If you can verify that data is in Elasticsearch using a tool like http://www.elastichq.org/ then I'd say your problem is in the Kibana config. Make sure the time horizing you're using will encompass the data timestamps you're trying to track.

**Comment by jptoto** [comment]
@shyamhd I may need some more information here. No data is showing in Kibana? Is Kibana correctly connected to Elasticsearch? Does any information show at all in Kibana? If you can verify that data is in Elasticsearch using a tool like http://www.elastichq.org/ then I'd say your problem is in the Kibana config. Make sure the time horizing you're using will encompass the data timestamps you're trying to track.

**Comment by joenmaes** [comment]
I ran today in the same "(406) Not Acceptable" error when I tried to run the sample project in combination with ElasticSearch 6.5.4
The problem was related to the old packages referenced in the sample project and resolved after updating to the latest stable version.

**Comment by jptoto** [comment]
Thanks for the note @joenmaes I'll update the sample project and push it up.
